# Master Snakefile

samples_dict = config["samples"]
sample_ids = samples_dict.keys()

rule all:
    input:
        expand("output/{sample}/bam/hpv_reads.bam.bai", sample=sample_ids),
		expand("output/{sample}/bam/methyl_hpv_reads.bam.bai", sample=sample_ids),
		expand("output/{sample}/methylation/hpv_methylation_frequency.tsv", sample=sample_ids),
        expand("output/{sample}/methylation/event_methyl_freq.tsv", sample=sample_ids),
        expand("output/{sample}/.combined/events_combined1.txt", sample=sample_ids),
		expand("output/{sample}/.combined/events_combined2.txt", sample=sample_ids),
		expand("output/{sample}/.combined/events_combined3.txt", sample=sample_ids),
        expand("output/{sample}/.combined/events_combined4.txt", sample=sample_ids),
        expand("output/{sample}/.combined/events_combined5.txt", sample=sample_ids)
        expand("output/{sample}/intType/{event}/intTest1.txt", sample=sample_ids, event=EVENTS),
        expand("output/{sample}/events/{event}_SVsubset.bedpe", sample=sample_ids, event=EVENTS),
        expand("output/{sample}/events/{event}_SVsubset.bed", sample=sample_ids, event=EVENTS)
		expand("output/{sample}/intType/{event}/intTest2.txt", sample=sample_ids, event=tbe),
        expand("output/{sample}/intType/{event}/genic_test/event_location.txt" , sample=sample_ids, event=tbe),
        expand("output/{sample}/methylation/regions/{event}/methylregions.bed", sample=sample_ids, event=tbe),
        expand("output/{sample}/intType/{event}/intTest3.txt", sample=sample_ids, event=eventsASM),
        expand("output/{sample}/intType/{event}/integration_type.txt", sample=sample_ids, event=EVENTS),
        expand("output/{sample}/methylation/dmrHotspotIntersectHPV.bed", sample=sample_ids),
        expand("output/{sample}/methylation/dmrIntersectHPV.bed", sample=sample_ids),
        expand("output/{sample}/methylation/densityPlotDMRs.png", sample=sample_ids),
        expand("output/{sample}/methylation/dmrHotspotIntersectHPV-wa.bed", sample=sample_ids),
        expand("output/{sample}/event_phase/{event}/hpv_phaseblock_hp.txt", sample=sample_ids, event=EVENTS),
        expand("output/{sample}/event_phase/{event}/dmr_permute/plottingDensityValues.txt", sample=sample_ids, event=EVENT)

include: "workflows/call_integration.snakefile"
include: "workflows/intTypeTest1.snakefile"
include: "workflows/intTypeTest2.snakefile"
include: "workflows/intTypeTest3.snakefile"
include: "workflows/intTypeTestFinal.snakefile"
include: "workflows/dmrAnalysis.snakefile"
include: "workflows/dmrAnalysis2.snakefile"
include: "workflows/dmrAnalysis3.snakefile"